rules:
  idiomatic:
    no-defined-entrypoint:
      level: ignore
    prefer-set-or-object-rule:
      ignore:
        files:
          - cheats/comprehensions/sets/cheat.rego
          - cheats/comprehensions/objects/cheat.rego
  imports:
    # ignore rego.v1 imports as they'd make examples more verbose.
    use-rego-v1:
      level: ignore
    implicit-future-keywords:
      level: ignore
  style:
    opa-fmt:
      ignore:
        files:
          - cheats/builtins/aggregates/cheat.rego
          - cheats/builtins/objects/cheat.rego
          - cheats/builtins/strings/cheat.rego
          - cheats/control_flow/or/cheat.rego
          - cheats/rules/complete/cheat.rego
  testing:
    file-missing-test-suffix:
      ignore:
        files:
          - cheats/testing/with/cheat.rego
    print-or-trace-call:
      ignore:
        files:
          - cheats/debugging/print/cheat.rego
    test-outside-test-package:
      ignore:
        files:
          - cheats/testing/with/cheat.rego
