name: Check

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-cheats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: StyraInc/setup-regal@main
        with:
          version: latest
      - run: regal lint --format github cheats
